export const MALE_RIDES = [
  {
    id: 1,
    name: "RidePool Basic",
    image:
      "https://firebasestorage.googleapis.com/v0/b/ride-away-app.appspot.com/o/basic.jpeg?alt=media&token=8d04d601-85b5-4839-8628-4dbad8dbdd29",
    multiplier: 1,
    time: 5,
  },
  {
    id: 2,
    name: "RidePool Lux",
    image:
      "https://firebasestorage.googleapis.com/v0/b/ride-away-app.appspot.com/o/Circle.png?alt=media&token=4020f262-dd12-4c0a-a35d-45a9308ae7a0",
    multiplier: 1.5,
    time: 4,
  },
  {
    id: 3,
    name: "RidePool Eco",
    image:
      "https://firebasestorage.googleapis.com/v0/b/ride-away-app.appspot.com/o/Slider.png?alt=media&token=c8ea89d7-4bfc-474c-9dfa-0d1c010d0d4d",
    multiplier: 1.75,
    time: 5,
  },
];
export const FEMALE_RIDES = [
  {
    id: 1,
    name: "RidePool Basic",
    image:
      "https://firebasestorage.googleapis.com/v0/b/ride-away-app.appspot.com/o/basic.jpeg?alt=media&token=8d04d601-85b5-4839-8628-4dbad8dbdd29",
    multiplier: 1,
    time: 5,
  },
  {
    id: 2,
    name: "RidePool Pink",
    image:
      "https://firebasestorage.googleapis.com/v0/b/ride-away-app.appspot.com/o/pink.png?alt=media&token=79118393-2f4f-4c94-95a9-13254d1b8cfb",
    multiplier: 1.5,
    time: 4,
  },
  {
    id: 3,
    name: "RidePool Eco",
    image:
      "https://firebasestorage.googleapis.com/v0/b/ride-away-app.appspot.com/o/Slider.png?alt=media&token=c8ea89d7-4bfc-474c-9dfa-0d1c010d0d4d",
    multiplier: 1.75,
    time: 5,
  },
];
export const SURGE_CHARGE = 2.5;

export const genders = [
  {
    id: 1,
    name: "Both",
  },
  {
    id: 2,
    name: "Male",
  },
  {
    id: 3,
    name: "Female",
  },
];

export const languages = [
  {
    id: 1,
    name: "English",
  },
  {
    id: 2,
    name: "Spanish",
  },
  {
    id: 3,
    name: "Hindi",
  },
  {
    id: 4,
    name: "German",
  },
  {
    id: 5,
    name: "Italian",
  },
  {
    id: 6,
    name: "Arabic",
  },
  {
    id: 7,
    name: "French",
  },
  {
    id: 8,
    name: "Chinese",
  },
  {
    id: 9,
    name: "Japanese",
  },
  {
    id: 10,
    name: "Russian",
  },

  {
    id: 11,
    name: "Korean",
  },
  {
    id: 12,
    name: "Telugu",
  },
];

export const drivers = [
  {
    name: "Kristian Bartoletti",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/90.jpg",
    gender: "Male",
    phone: "1-336-495-7963",
    vehicle: "Jeep Beetle",
    model: "Land Cruiser",
    licensePlate: "LI62SUG",
    languages: ["Italian", "English", "Telugu", "Korean"],
  },
  {
    name: "Jaiden Kessler",
    avatarUrl: "https://avatars.githubusercontent.com/u/40711253",
    gender: "Male",
    phone: "1-400-449-1669",
    vehicle: "Polestar Escalade",
    model: "Roadster",
    licensePlate: "AS03VZY",
    languages: ["French", "Telugu", "English", "German"],
  },
  {
    name: "Geovanni Gutmann",
    avatarUrl: "https://avatars.githubusercontent.com/u/99311292",
    gender: "Female",
    phone: "1-431-927-2954",
    vehicle: "Volkswagen Malibu",
    model: "Beetle",
    licensePlate: "KK35LDC",
    languages: ["French", "Telugu"],
  },
  {
    name: "Hazle Koelpin-Simonis",
    avatarUrl: "https://avatars.githubusercontent.com/u/56950981",
    gender: "Female",
    phone: "(498) 356-7387",
    vehicle: "Aston Martin Civic",
    model: "Ranchero",
    licensePlate: "MD75ITM",
    languages: ["Spanish", "Arabic", "English"],
  },
  {
    name: "Alicia Pouros",
    avatarUrl: "https://avatars.githubusercontent.com/u/46999424",
    gender: "Male",
    phone: "1-952-619-3831",
    vehicle: "Bentley Mercielago",
    model: "A4",
    licensePlate: "PX79HAE",
    languages: ["Russian", "Japanese"],
  },
  {
    name: "Oceane Bernhard",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/259.jpg",
    gender: "Female",
    phone: "969-915-4094",
    vehicle: "Maserati Model Y",
    model: "Aventador",
    licensePlate: "PH32MML",
    languages: ["Japanese", "Chinese"],
  },
  {
    name: "Neva Bogan",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/420.jpg",
    gender: "Male",
    phone: "(511) 670-9352",
    vehicle: "Aston Martin Camaro",
    model: "Colorado",
    licensePlate: "XD88VMO",
    languages: ["Spanish", "Korean"],
  },
  {
    name: "Carleton Haley-Haley",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/716.jpg",
    gender: "Female",
    phone: "253-619-9743",
    vehicle: "Tesla Accord",
    model: "CX-9",
    licensePlate: "GD20IDS",
    languages: ["French", "Arabic", "English"],
  },
  {
    name: "Larissa Funk",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1025.jpg",
    gender: "Female",
    phone: "1-312-482-1797",
    vehicle: "Tesla XC90",
    model: "Volt",
    licensePlate: "KV20ZFP",
    languages: ["Russian", "Japanese", "German"],
  },
  {
    name: "Shakira Hirthe",
    avatarUrl: "https://avatars.githubusercontent.com/u/36367644",
    gender: "Male",
    phone: "360-319-3959",
    vehicle: "Maserati 2",
    model: "XTS",
    licensePlate: "LG73AJY",
    languages: ["Arabic", "Hindi", "Italian", "Spanish"],
  },
  {
    name: "Shane Ernser",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/823.jpg",
    gender: "Female",
    phone: "297-762-2044",
    vehicle: "BMW Charger",
    model: "Golf",
    licensePlate: "DM53FTM",
    languages: ["Spanish", "Telugu", "German"],
  },
  {
    name: "Bernardo Breitenberg",
    avatarUrl: "https://avatars.githubusercontent.com/u/4674843",
    gender: "Female",
    phone: "597-971-9136",
    vehicle: "Volkswagen 1",
    model: "Golf",
    licensePlate: "NZ03MZH",
    languages: ["German", "Korean"],
  },
  {
    name: "Oleta Heaney",
    avatarUrl: "https://avatars.githubusercontent.com/u/21306315",
    gender: "Female",
    phone: "(935) 775-2937",
    vehicle: "Chrysler Explorer",
    model: "CTS",
    licensePlate: "AV19RHB",
    languages: ["Italian", "Korean"],
  },
  {
    name: "Cassandre Kirlin",
    avatarUrl: "https://avatars.githubusercontent.com/u/82865407",
    gender: "Male",
    phone: "1-371-642-6639",
    vehicle: "Mini Land Cruiser",
    model: "Grand Cherokee",
    licensePlate: "VU50KFE",
    languages: ["Italian", "English", "Korean", "German"],
  },
  {
    name: "Nelle Bins",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1220.jpg",
    gender: "Male",
    phone: "630-331-4489",
    vehicle: "Smart Aventador",
    model: "Civic",
    licensePlate: "BC49AYW",
    languages: ["German", "Japanese"],
  },
  {
    name: "Liliane Prohaska",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/847.jpg",
    gender: "Female",
    phone: "268-369-9131",
    vehicle: "BMW Focus",
    model: "Civic",
    licensePlate: "LN69YJB",
    languages: ["Japanese", "Korean", "Chinese", "Russian"],
  },
  {
    name: "Erin Smitham",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/544.jpg",
    gender: "Male",
    phone: "466-820-7879",
    vehicle: "Polestar Beetle",
    model: "Model T",
    licensePlate: "TA94FCP",
    languages: ["German", "Russian", "French"],
  },
  {
    name: "Malachi Greenfelder",
    avatarUrl: "https://avatars.githubusercontent.com/u/84241615",
    gender: "Male",
    phone: "862-945-5365",
    vehicle: "Audi Accord",
    model: "Cruze",
    licensePlate: "CZ79FHM",
    languages: ["Italian", "Chinese"],
  },
  {
    name: "Linnea Gulgowski",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/627.jpg",
    gender: "Female",
    phone: "883-591-7035",
    vehicle: "Volvo CTS",
    model: "Volt",
    licensePlate: "LB34UFY",
    languages: ["Spanish", "German", "Japanese", "Telugu"],
  },
  {
    name: "Camylle Murazik",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1112.jpg",
    gender: "Male",
    phone: "640-959-7012",
    vehicle: "BMW Explorer",
    model: "Expedition",
    licensePlate: "IM03ALU",
    languages: ["Telugu", "German"],
  },
  {
    name: "Kaycee Bogisich",
    avatarUrl: "https://avatars.githubusercontent.com/u/43429301",
    gender: "Female",
    phone: "915-819-6408",
    vehicle: "Hyundai Aventador",
    model: "Element",
    licensePlate: "ZG71PCK",
    languages: ["Russian", "Telugu", "German"],
  },
  {
    name: "Geraldine Bernhard",
    avatarUrl: "https://avatars.githubusercontent.com/u/92604226",
    gender: "Female",
    phone: "280-945-1841",
    vehicle: "Jeep Model T",
    model: "Charger",
    licensePlate: "AR10KIN",
    languages: ["English", "Telugu", "Hindi", "Russian"],
  },
  {
    name: "Ashly Terry",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/79.jpg",
    gender: "Female",
    phone: "882-440-0492",
    vehicle: "Mazda Mustang",
    model: "Model T",
    licensePlate: "LT79EGZ",
    languages: ["German", "Korean"],
  },
  {
    name: "Price Heaney-Gerhold",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/966.jpg",
    gender: "Male",
    phone: "1-388-934-2622",
    vehicle: "Nissan Durango",
    model: "Durango",
    licensePlate: "HP39YJT",
    languages: ["German", "Telugu", "French", "English"],
  },
  {
    name: "Damian Bernier",
    avatarUrl: "https://avatars.githubusercontent.com/u/41010643",
    gender: "Female",
    phone: "1-520-872-0342",
    vehicle: "Audi Spyder",
    model: "Corvette",
    licensePlate: "MI25TWV",
    languages: ["Japanese", "English"],
  },
  {
    name: "Asa Wisozk",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1017.jpg",
    gender: "Female",
    phone: "1-586-731-4138",
    vehicle: "Bentley Aventador",
    model: "Corvette",
    licensePlate: "XH89NCK",
    languages: ["German", "Korean", "Arabic"],
  },
  {
    name: "Kevon Cremin",
    avatarUrl: "https://avatars.githubusercontent.com/u/7683293",
    gender: "Female",
    phone: "(256) 266-2092",
    vehicle: "Porsche Model X",
    model: "Malibu",
    licensePlate: "KX80HDM",
    languages: ["Italian", "English", "German", "Japanese"],
  },
  {
    name: "Ines Okuneva",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1001.jpg",
    gender: "Male",
    phone: "1-488-560-7033",
    vehicle: "Volkswagen Model Y",
    model: "Model X",
    licensePlate: "CQ91BCD",
    languages: ["Italian", "Telugu", "Chinese"],
  },
  {
    name: "Clyde Ferry",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/228.jpg",
    gender: "Female",
    phone: "436-647-8315",
    vehicle: "Mini Colorado",
    model: "Corvette",
    licensePlate: "IQ92UON",
    languages: ["French", "Russian", "English"],
  },
  {
    name: "Danyka Metz",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/629.jpg",
    gender: "Female",
    phone: "667-820-1733",
    vehicle: "Lamborghini LeBaron",
    model: "911",
    licensePlate: "JH97JCX",
    languages: ["Spanish", "Arabic", "Chinese"],
  },
  {
    name: "Danika Auer",
    avatarUrl: "https://avatars.githubusercontent.com/u/52052364",
    gender: "Male",
    phone: "1-692-630-2073",
    vehicle: "Mini Cruze",
    model: "Accord",
    licensePlate: "FD13TVV",
    languages: ["Chinese", "French", "Arabic", "Korean"],
  },
  {
    name: "Charlotte Kautzer",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/231.jpg",
    gender: "Female",
    phone: "(805) 789-7691",
    vehicle: "Polestar Countach",
    model: "Aventador",
    licensePlate: "PE85GAW",
    languages: ["Korean", "Chinese", "Russian"],
  },
  {
    name: "Monroe Daugherty",
    avatarUrl: "https://avatars.githubusercontent.com/u/88397601",
    gender: "Male",
    phone: "1-925-736-4728",
    vehicle: "Smart Altima",
    model: "Cruze",
    licensePlate: "DG90UWM",
    languages: ["Italian", "Telugu", "Korean"],
  },
  {
    name: "Chanelle Schowalter",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/320.jpg",
    gender: "Female",
    phone: "785-616-5405",
    vehicle: "Volkswagen Grand Cherokee",
    model: "Escalade",
    licensePlate: "ZU42EQJ",
    languages: ["Russian", "French", "German"],
  },
  {
    name: "Pascale Corkery",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/909.jpg",
    gender: "Male",
    phone: "1-622-486-4190",
    vehicle: "Jaguar Colorado",
    model: "Volt",
    licensePlate: "KZ51OPZ",
    languages: ["Korean", "Chinese", "Japanese", "Russian"],
  },
  {
    name: "Cicero Lemke",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/406.jpg",
    gender: "Female",
    phone: "643-938-8715",
    vehicle: "Fiat Challenger",
    model: "Land Cruiser",
    licensePlate: "AE98RDB",
    languages: ["Hindi", "Korean"],
  },
  {
    name: "Jeromy Bartoletti",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/218.jpg",
    gender: "Female",
    phone: "831-535-0787",
    vehicle: "Nissan Element",
    model: "Beetle",
    licensePlate: "VY32MRM",
    languages: ["Telugu", "German"],
  },
  {
    name: "Maxine Schuppe",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/345.jpg",
    gender: "Female",
    phone: "329-267-0038",
    vehicle: "Jaguar A4",
    model: "Impala",
    licensePlate: "LP00NGD",
    languages: ["Korean", "French"],
  },
  {
    name: "Eva Reilly",
    avatarUrl: "https://avatars.githubusercontent.com/u/26448868",
    gender: "Male",
    phone: "568-881-0366",
    vehicle: "Rolls Royce Countach",
    model: "Model X",
    licensePlate: "VV66OLT",
    languages: ["German", "Chinese"],
  },
  {
    name: "Rolando Moen",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/670.jpg",
    gender: "Male",
    phone: "208-432-0050",
    vehicle: "Nissan CX-9",
    model: "Prius",
    licensePlate: "LK93CBZ",
    languages: ["French", "German"],
  },
  {
    name: "Avis Lind",
    avatarUrl: "https://avatars.githubusercontent.com/u/63679783",
    gender: "Male",
    phone: "391-886-4175",
    vehicle: "Dodge Altima",
    model: "Challenger",
    licensePlate: "VQ82DLS",
    languages: ["French", "Arabic", "Italian"],
  },
  {
    name: "Joaquin Lesch",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/898.jpg",
    gender: "Female",
    phone: "(383) 203-9912",
    vehicle: "Land Rover Camaro",
    model: "Caravan",
    licensePlate: "CT81IDS",
    languages: ["Japanese", "Russian", "Spanish"],
  },
  {
    name: "Charles Mertz",
    avatarUrl: "https://avatars.githubusercontent.com/u/46287845",
    gender: "Female",
    phone: "669-690-7163",
    vehicle: "Volkswagen Prius",
    model: "1",
    licensePlate: "HC52XIV",
    languages: ["Russian", "Chinese", "French", "Spanish"],
  },
  {
    name: "Patsy Berge",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/8.jpg",
    gender: "Male",
    phone: "797-386-1610",
    vehicle: "Bentley Focus",
    model: "Model T",
    licensePlate: "IP32LNI",
    languages: ["Russian", "Japanese", "Chinese", "German"],
  },
  {
    name: "Alysa Kilback",
    avatarUrl: "https://avatars.githubusercontent.com/u/71584067",
    gender: "Female",
    phone: "272-513-6012",
    vehicle: "Land Rover Aventador",
    model: "CTS",
    licensePlate: "IS88CEZ",
    languages: ["Hindi", "Arabic", "Telugu", "German"],
  },
  {
    name: "Myrtis Crist",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/218.jpg",
    gender: "Male",
    phone: "(844) 291-8905",
    vehicle: "BMW Mustang",
    model: "Jetta",
    licensePlate: "FR66MQT",
    languages: ["Telugu", "Spanish", "Italian"],
  },
  {
    name: "Damaris Rolfson",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1197.jpg",
    gender: "Female",
    phone: "(810) 232-8506",
    vehicle: "Volkswagen Fortwo",
    model: "Countach",
    licensePlate: "YZ10WVN",
    languages: ["German", "Spanish", "Japanese", "Chinese"],
  },
  {
    name: "Tyrel Botsford",
    avatarUrl: "https://avatars.githubusercontent.com/u/43229222",
    gender: "Male",
    phone: "630-401-6655",
    vehicle: "Dodge CTS",
    model: "Model T",
    licensePlate: "XD44GJA",
    languages: ["Italian", "Korean"],
  },
  {
    name: "Bernard Buckridge",
    avatarUrl: "https://avatars.githubusercontent.com/u/58422149",
    gender: "Female",
    phone: "971-612-3974",
    vehicle: "Honda Colorado",
    model: "Accord",
    licensePlate: "VI11LJM",
    languages: ["German", "Russian", "Korean", "Spanish"],
  },
  {
    name: "Jeromy Langworth",
    avatarUrl:
      "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/980.jpg",
    gender: "Male",
    phone: "(606) 874-9845",
    vehicle: "Ferrari Expedition",
    model: "Wrangler",
    licensePlate: "HF75SOK",
    languages: ["Hindi", "Chinese"],
  },
];
